"""Data structures produced by the deepfake detection layer."""

import struct
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class DeepfakePrediction:
    """A single inference result derived from actual model output."""

    ai_probability: float
    real_probability: float
    predicted_class: str
    model_name: str
    model_version: str
    device: str

    def as_dict(self) -> dict:
        """Plain-dict view used by the API layer."""
        return {
            "ai_probability": self.ai_probability,
            "real_probability": self.real_probability,
            "predicted_class": self.predicted_class,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "device": self.device,
        }


@dataclass(frozen=True)
class DetectorStatus:
    """Reported model-manager state (accurate, never guessed)."""

    state: str  # "not_loaded" | "loading" | "loaded" | "unavailable"
    model_name: str | None = None
    model_version: str | None = None
    device: str | None = None


@dataclass(frozen=True)
class SpeakerEmbedding:
    """A deterministic L2-normalized speaker embedding from the model.

    The embedding is generated by actual model inference. It is stored
    L2-normalized (unit length) so cosine similarity reduces to a dot
    product; this is expressed explicitly and never assumed implicitly.
    """

    vector: np.ndarray  # shape (embedding_dim,)
    model_name: str
    model_version: str
    device: str
    embedding_dim: int

    def to_bytes(self) -> bytes:
        """Serialize to a compact float32 byte string (dimension-prefixed)."""
        return struct.pack("<I", self.embedding_dim) + self.vector.astype(
            np.float32
        ).tobytes()

    @classmethod
    def from_bytes(
        cls, payload: bytes, model_name: str, model_version: str, device: str
    ) -> "SpeakerEmbedding":
        dim = struct.unpack("<I", payload[:4])[0]
        expected = 4 + dim * 4
        if len(payload) != expected:
            raise ValueError("Embedding payload length does not match its dimension.")
        vector = np.frombuffer(payload, dtype=np.float32, offset=4).copy()
        return cls(
            vector=vector,
            model_name=model_name,
            model_version=model_version,
            device=device,
            embedding_dim=dim,
        )

    def to_dict(self) -> dict:
        """Never returned to the client - used only within the backend layer."""
        return {
            "embedding_dim": self.embedding_dim,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "device": self.device,
        }


@dataclass(frozen=True)
class SpeakerVerificationResult:
    """Output of a speaker verification comparison (actual model values)."""

    similarity: float  # cosine similarity in [-1, 1]
    verified: bool
    embedding_model: str
    embedding_model_version: str
    device: str